apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/demoapp/config"   # путь в Vault (KV v2)
type: Opaque
stringData:
  username: <placeholder>
  password: <placeholder>
