# .github/workflows/123.yml
name: Build and Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Environment'
        required: true
        type: string
      EXPECTED_HASH:
        description: 'Expected SHA-256 hash of the secret'
        required: true
        type: string
    secrets:
      SECRET:
        description: 'Kubernetes Config Secret'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ inputs.ENVIRONMENT }}
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "ENVIRONMENT=${{ inputs.ENVIRONMENT }}" >> $GITHUB_ENV
          COMPUTED_HASH=$(echo -n "$SECRET" | sha256sum | awk '{print $1}')
          if [ "$COMPUTED_HASH" = "${{ inputs.EXPECTED_HASH }}" ]; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_ENV
        env:
          SECRET: ${{ secrets.SECRET }}
