# .github/workflows/123.yml
name: Build and Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Deployment Environment'
        required: true
        type: string
      COMMON_VAR:
        description: 'Common Variable for Deployment'
        required: true
        type: string
    secrets:
      SECRET:
        description: 'Kubernetes Config Secret'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}    # Указание окружения для доступа к его переменным и секретам
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if COMMON_VAR is set
        run: |
          if [ -z "${COMMON_VAR}" ]; then
            echo "COMMON_VAR is not set."
          else
            echo "COMMON_VAR is set."
          fi
        env:
          COMMON_VAR: ${{ inputs.COMMON_VAR }}

      - name: Check if SECRET is set
        run: |
          if [ -z "${SECRET}" ]; then
            echo "SECRET is not set."
          else
            echo "SECRET is set."
          fi
        env:
          SECRET: ${{ secrets.SECRET }}