# .github/workflows/123.yml
name: Build and Deploy

on:
  workflow_call:
    inputs:
      COMMON_VAR:
        description: 'Common variable'
        required: true
        type: string
      ENVIRONMENT:
        description: 'Environment'
        required: true
        type: string
    secrets:
      SECRET:
        description: 'Kubernetes Config Secret'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ inputs.ENVIRONMENT }}
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "COMMON_VAR=${{ inputs.COMMON_VAR }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ inputs.ENVIRONMENT }}" >> $GITHUB_ENV
          echo "APP_NAMESPACE=${{ secrets.SECRET }}" >> $GITHUB_ENV
          cat $GITHUB_ENV
