name: Build and Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "Environment name"
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # This ties the job to the chosen environment (development or production).
    # GitHub will inject any environment-level variables (and secrets) defined there.
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print environment variables
        run: |
          echo "Environment is: ${{ inputs.ENVIRONMENT }}"
          echo "COMMON_VAR (from environment) is: $COMMON_VAR"
          echo "ANOTHER_VAR (from environment) is: $ANOTHER_VAR"
