name: Build and Deploy

on:
  workflow_call:
    inputs:
      COMMON_VAR:
        description: 'variable'
        required: true
        type: string
      ENVIRONMENT:
        description: 'ENVIRONMENT'
        required: true
        type: string
    secrets:
      SECRET:
        description: 'secret'
        required: true

jobs:
  build-and-deploy:
    runs-on: self-hosted
    name: testing
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "COMMON_VAR=${{ inputs.COMMON_VAR }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ inputs.ENVIRONMENT }}" >> $GITHUB_ENV
          echo "APP_NAMESPACE=${{ secrets.SECRET }}" >> $GITHUB_ENV
          cat $GITHUB_ENV