name: Build and Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: "Deployment Environment"
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Dynamically use the environment passed from caller
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show environment variable
        run: |
          echo "COMMON_VAR from environment: $COMMON_VAR"
