# .github/workflows/123.yml
name: Build and Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Environment'
        required: true
        type: string
      COMMON_VAR:
        description: 'common var'
        required: true
        type: string
    secrets:
      SECRET:
        description: 'Kubernetes Config Secret'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}    # Указание окружения для доступа к его переменным и секретам
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "COMMON_VAR=${{ env.COMMON_VAR }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ inputs.ENVIRONMENT }}" >> $GITHUB_ENV
          echo "APP_NAMESPACE=${{ secrets.SECRET }}" >> $GITHUB_ENV
        env:
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
          COMMON_VAR: ${{ inputs.COMMON_VAR }}
          APP_NAMESPACE: ${{ secrets.SECRET }}

      - name: Check if SECRET is set
        run: |
          if [ -z "${SECRET}" ]; then
            echo "SECRET is not set."
            exit 1
          else
            echo "SECRET is set."
          fi
        env:
          SECRET: ${{ secrets.SECRET }}
    