name: Build and Deploy

on:
  workflow_call:
    inputs:
      COMMON_VAR:
        description: 'Common variable'
        required: true
        type: string
      ENVIRONMENT:
        description: 'Environment'
        required: true
        type: string
      EXPECTED_HASH:  # New input for expected hash
        description: 'Expected SHA-256 hash of the secret'
        required: true
        type: string
    secrets:
      SECRET:
        description: 'Kubernetes Config Secret'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ inputs.ENVIRONMENT }}
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "COMMON_VAR=${{ inputs.COMMON_VAR }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ inputs.ENVIRONMENT }}" >> $GITHUB_ENV

      - name: Verify Secret Hash
        id: secret_check
        run: |
          # Compute SHA-256 hash of the secret
          COMPUTED_HASH=$(echo -n "$SECRET" | sha256sum | awk '{print $1}')
          
          # Compare with expected hash
          if [ "$COMPUTED_HASH" = "${{ inputs.EXPECTED_HASH }}" ]; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi
        env:
          SECRET: ${{ secrets.SECRET }}  # Secret is only used here
