name: Deploy Environments

on:
  push:
    branches:
      - develop
    tags:
      - "v*"

jobs:
  deploy-dev:
    # Only run when pushing to the 'develop' branch
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/123.yml
    with:
      ENVIRONMENT: development

  deploy-prod:
    # Only run when pushing a tag like 'v1.0', 'v2.3' etc.
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/123.yml
    with:
      ENVIRONMENT: production