name: Deploy Environments

on:
  push:
    branches:
      - develop      # Триггер при пушах в ветку develop
    tags:
      - 'v*'         # Триггер при пушах тегов, начинающихся с 'v'

jobs:
  # ==========================
  #       DEV / Develop
  test-dev:
    if: github.ref == 'refs/heads/develop'   # Условие запуска: пуш в ветку develop
    uses: ./.github/workflows/123.yml
    with:
      COMMON_VAR: ${{ secrets.COMMON_VAR }}     # Передаём переменную из среды
      ENVIRONMENT: 'development'               # Явно указываем окружение
    secrets:
      SECRET: ${{ secrets.SECRET }}            # Передаём секрет из среды
    environment:
      name: development                         # Указываем среду

  # ==========================
  #       PROD / Production
  test-prod:
    if: startsWith(github.ref, 'refs/tags/v') # Условие запуска: пуш тега, начинающегося с 'v'
    uses: ./.github/workflows/123.yml
    with:
      COMMON_VAR: ${{ secrets.COMMON_VAR }}     # Передаём переменную из среды
      ENVIRONMENT: 'production'                # Явно указываем окружение
    secrets:
      SECRET: ${{ secrets.SECRET }}            # Передаём секрет из среды
    environment:
      name: production                          # Указываем среду
