# .github/workflows/test.yml
name: Deploy Environments

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  # ==========================
  #       DEV / Develop
  test-dev:
    if: github.ref == 'refs/heads/develop'   # Запуск только при пуше в ветку develop
    uses: ./.github/workflows/123.yml       # Вызов Reusable Workflow
    with:
      ENVIRONMENT: 'development'             # Передача окружения как входного параметра
      COMMON_VAR: ${{ vars.COMMON_VAR }}       # Передача COMMON_VAR из репозиторных переменных

    secrets:
      SECRET: ${{ secrets.SECRET }}  # Передача секрета для разработки

  # ==========================
  #       PROD / Production
  test-prod:
    if: startsWith(github.ref, 'refs/tags/v') # Запуск только при пуше тегов, начинающихся с 'v'
    uses: ./.github/workflows/123.yml         # Вызов Reusable Workflow
    with:
      ENVIRONMENT: 'production'                # Передача окружения как входного параметра
      COMMON_VAR: ${{ vars.COMMON_VAR }}       # Передача COMMON_VAR из репозиторных переменных
    secrets:
      SECRET: ${{ secrets.SECRET }}       # Передача секрета для продакшена