name: Deploy Environments

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  test-dev:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/123.yml
    with:
      COMMON_VAR: ${{ vars.COMMON_VAR }}
      ENVIRONMENT: 'develop'
    secrets:
      SECRET: ${{ secrets.DEVELOP_SECRET }}

  test-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/123.yml
    with:
      COMMON_VAR: ${{ vars.PROD_COMMON_VAR }}
      ENVIRONMENT: 'production'
    secrets:
      SECRET: ${{ secrets.PROD_SECRET }}
