# .github/workflows/deploy.yml
name: Deploy Environments

on:
  push:
    branches:
      - develop      # Триггер при пушах в ветку develop
    tags:
      - 'v*'         # Триггер при пушах тегов, начинающихся с 'v'

jobs:
  # ==========================
  #       DEV / Develop
  test-dev:
    if: github.ref == 'refs/heads/develop'   # Условие запуска: пуш в ветку develop
    environment: development                 # Указание среды
    uses: ./.github/workflows/123.yml        # Использование Reusable Workflow
    with:
      COMMON_VAR: ${{ env.COMMON_VAR }}       # Передача переменной окружения
      ENVIRONMENT: 'development'             # Явное указание окружения
    secrets:
      SECRET: ${{ secrets.SECRET }}          # Передача секрета из среды

  # ==========================
  #       PROD / Production
  test-prod:
    if: startsWith(github.ref, 'refs/tags/v') # Условие запуска: пуш тега, начинающегося с 'v'
    environment: production                    # Указание среды
    uses: ./.github/workflows/123.yml          # Использование Reusable Workflow
    with:
      COMMON_VAR: ${{ env.COMMON_VAR }}         # Передача переменной окружения
      ENVIRONMENT: 'production'                # Явное указание окружения
    secrets:
      SECRET: ${{ secrets.SECRET }}            # Передача секрета из среды
